# variables.tf
#
# WHAT THIS FILE DOES:
# Declares every input this Terraform/OpenTofu configuration accepts, with
# a type, a description, and (where safe) a sensible default. Nothing in
# main.tf should have a hardcoded value that you might reasonably want to
# change later (region, instance size, your IP, your key pair name) —
# that's what variables are for.
#
# WHY THIS MATTERS FOR LEARNING:
# This is the difference between a one-off script and reusable IaC. A
# bash script with `aws ec2 run-instances --instance-type t3.small ...`
# baked in only works for you, today, on this account. A parameterized
# Terraform module can be re-run for a different region, a different
# instance size, or a different person's key pair without editing the
# core logic — you only touch the values, never the resource definitions.
#
# You'll supply real values for these either via a terraform.tfvars file
# (see terraform.tfvars.example) or with -var flags on the command line.

variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = <<-EOT
    EC2 instance type. Kept as a variable (not hardcoded) so you can
    bump it later if you move off the free/credit plan. t3.small is the
    largest type selectable under AWS's newer credit-based free plan as
    of this writing — 2 vCPU, 2GB RAM. k3s fits comfortably here where a
    full kubeadm-built cluster would not.
  EOT
  type    = string
  default = "t3.small"
}

variable "key_pair_name" {
  description = <<-EOT
    Name of an EXISTING EC2 key pair (the .pem you already generated in
    the AWS console, e.g. "jenops_key_pair"). Terraform does not create
    this for you on purpose — private keys generated by Terraform end up
    written into your state file, which is a secret-leakage risk. Bring
    your own key pair instead.
  EOT
  type = string
}

variable "my_ip_cidr" {
  description = <<-EOT
    Your current public IP, in CIDR notation (e.g. "203.0.113.4/32"),
    used to scope the security group's SSH and app-port rules to just
    you instead of the whole internet (0.0.0.0/0). Find yours with:
      curl -s ifconfig.me
    then append /32.
  EOT
  type = string
}

variable "app_port" {
  description = <<-EOT
    Port your sample application listens on inside the cluster and that
    you'll reach it on externally via a NodePort or port-forward. Kept
    as a variable so the security group rule and the k8s Service manifest
    can be told to agree on the same number.
  EOT
  type    = number
  default = 30080
}

variable "project_name" {
  description = "Short name used to tag/prefix all resources this project creates, so they're easy to find (and delete) in the AWS console."
  type        = string
  default     = "k8s-cicd-lab"
}
